### ISSUE TITLE
#21 get the missing week 4 things working

### ISSUE THREAD

**Issue by lisja** [lisja/KIK-LG211_HALM#21]
1. Get the 3 different search engines working in the UI:  (@shimley was doing this, right?)
    - boolean still missing the AND/OR/NOT 
    - stems and tfv completely

2. Some changes to the UI (make UI output "pretty" or at least a bit "prettier") (@lisja is doing this)
    - show the number of hits, separate the article names and the article (DONE)
    - **IF** there is time:
        - write the instructions on how to use the UI
        - create the "read more" button to show the whole text if wanted

**Comment by shimley** [comment]
I got the 1. part working. The code looks ugly in a lot of places but that's what it's like sometimes. Thank god this is not our final project : D

AND/OR/NOT is working also with the exception that for some reason it is AND/OR/AND NOT nowadays.

The instructions would be nice to have as well, though. Especially because of the AND/OR/AND NOT thing.
